### ISSUE TITLE
Failed to save device

### ISSUE THREAD

**Issue by dfairles** [f5devcentral/f5-big-ip-migration-assistant#1]
Error loading device.  See attached.  platform is OSX
![f5](https://user-images.githubusercontent.com/1858251/35123319-59b72496-fc67-11e7-9f0f-f3ed3ff44eaf.jpg)

**Comment by JoeReifel** [comment]
hi @dfairles, what version of BIG-IP is running on the device you're connecting to?  It appears that the device is retuning no json (that's the undefined part) but can connect to the device via https.  So it could be not a BIG-IP, or a version that's not supported.

**Comment by dfairles** [comment]
13.0HF3. I tried on a windows box and got the same error.  I have BigIQ, so I'm sure json is working.

**Comment by dfairles** [comment]
BTW, it also said I had a self signed cert so I had to turn off checking.  I do not have a self signed cert.

**Comment by JoeReifel** [comment]
Hi @dfairles, I was able to reproduce this on a BIG-IP device running v13.1.0 managed by BIG-IQ.  We're looking into it now.

**Comment by labilbo** [comment]
The TypeError issue has been patched in the next release (v1.0.2), which should be made available shortly

**Comment by dfairles** [comment]
Great!

**Comment by labilbo** [comment]
Hi @dfairles, the v1.0.2 release is now available- please let me know if it doesn't address the issues you were seeing.  Thanks!

**Comment by nambrosch** [comment]
i'm having the same issue w/version 1.0.2 on a 12.1.3 device.

**Comment by JoeReifel** [comment]
Hi @nambrosch, can you tell me a little about the BIG-IP devices and environment you are starting from?  Is it managed by BIG-IQ?  Is it a standard 2-device HA, or something different?  Any special hotfixes applied?  Anything else unusual that you think we should be aware of?

**Comment by nambrosch** [comment]
@JoeReifel viprion cluster, not big-iq, 2-device ha pair.  no engineering hotfixes.  note that i imported a ucs to a new device (different model) using platform-migrate which worked perfect.  i was also able to load a ucs into the migration assistant.

this may be unrelated (and may not be a bug?) but one thing i noticed that seemed weird is after taking a ucs and attempting the upgrade it tells me that "12.1.3.1 must be greater or equal to 12.1.3" - the new host is running 12.1.3.1, the old 12.1.3.

perhaps something to do w/viprion cluster?

**Comment by dfairles** [comment]
Viprion Cluster here too.  So something to do with Viprions.

**Comment by labilbo** [comment]
@dfairles @nambrosch could you try v1.0.3 ( https://github.com/f5devcentral/f5-big-ip-migration-assistant/releases/tag/v1.0.3 ) and see if it addresses the issues?

**Comment by labilbo** [comment]
Fixed in v1.0.3
