### ISSUE TITLE
I'm trying to migrate a cluster of VIPRION's vCMP 

### ISSUE THREAD

**Issue by gakadjame** [f5devcentral/f5-big-ip-migration-assistant#3]
Hello,
I am currently experiencing a problem when adding a f5 VIPRION running with version 12.1.2, yet I arrive at the same time to add another device that has the same version. As this one with which it is clustered . So it works for one and not for the other? In addition they are sync so they have the same configuration. I do not see what it could be like error for add the one else? I see this error :
TypeError : cannot read property '0' of undefined.

**Comment by JoeReifel** [comment]
hi @gakadjame, just gathering a bit more detail - what operation were you performing when you encountered this error, was it in the add device screen after entering credentials and clicking Save Device?  What version of Migration Assistant are you running, and what version of the vCMP instance are you connecting to?

**Comment by gakadjame** [comment]
Hello JoeReifel,
Yes, I just add the ip of the device on the migration tool in the add device tab. I am in version 12.1.2 on the vCMP instance and the migration assistant is in v1.0.1

**Comment by JoeReifel** [comment]
@gakadjame okay try using the v1.0.3 release available at https://github.com/f5devcentral/f5-big-ip-migration-assistant/releases - I think this was fixed in 1.0.2 but just to be sure.

**Comment by gakadjame** [comment]
OK thanks you, I'll get you feedback asap

**Comment by gakadjame** [comment]
@JoeReifel Hello Joel,
I just installed version 1.0.3 of the migration tool and I did the same test again and I noticed the errors on version 1.0.1. When adding a device
TypeError: Can not read the '0' property of undefined.

**Comment by gakadjame** [comment]
@JoeReifel ,

I think I'll upgrade my two VIPRIONS to version 12.0.3 which does not present this problem. I'll tell you what it means

**Comment by JoeReifel** [comment]
@gakadjame sorry I had you waste your time upgrading to 1.0.3, I was pretty certain it would work with version 1.0.3 and VIPRION.  On the VIPRIONS, any source version should work, especially in the 12.x generation.  

Please confirm for me the following, to make sure we're on the same page:

1. The VIPRIONs are the **source** devices that you want to get a ucs file from.  Your intention is to migrate the configuration to another device
2. The VIPRIONs are currently running version 12.1.2
3. You are not using vCMP on these VIPRIONs so we don't need to talk about vCMP guests and hosts
4. The error is occurring when adding the device (or is it when generating the ucs?)

**Comment by gakadjame** [comment]
@JoeReifel ,
OK, I confirm to you that all the established steps correspond to my model. just a detail, I have vCMP on VIPRIONs and these are the ones I want migrated, because my VIPRIONS frames have a hypervisor module that I use that hosts my source vCMPs.
Yes, I want to migrate its vCMPs to other vCMPs that are hosted on i7800 chassis. And my VIPRIONs cluster is currently running on version 12.1.2. And finally, I confirm that the error occurs exactly when I want to add my guests vCMPs VIPRIONS on the migration tool, yet I do not encounter this problem with the target I7800 guests who are in version 12.0.3.

**Comment by gakadjame** [comment]
@JoeReifel Hello,
I think the problem is related to the VIPRIONS chassis, because even after upgrading from version 12.0.3. I still have the same problem. I still can not add my equipment on the migration tool.
By cons everything works well with the chassis I7800. Is it possible to organize a webex to see in detail this incident?

**Comment by JoeReifel** [comment]
Hey @gakadjame, we have reproduced it internally which will help us isolate the problem quickly.  Thanks for reporting.

**Comment by labilbo** [comment]
Hi @gakadjame, we have a patch for this issue and will provide a new pre-release build for Windows shortly.  I'll update this thread when it's available.

**Comment by labilbo** [comment]
@gakadjame can you give this build a try and let us know if it addresses the issues you're seeing?  https://github.com/f5devcentral/f5-big-ip-migration-assistant/releases/tag/v1.0.4-beta

**Comment by gakadjame** [comment]
@labilbo  thank you for your comments, I use a windows machine so I wait for the patch windows to provide the test again with the new release that you will upload. Can you tell me when will it be available?

**Comment by labilbo** [comment]
Hi @gakadjame, the second link on that release page is for Windows ( https://github.com/f5devcentral/f5-big-ip-migration-assistant/releases/download/v1.0.4-beta/F5.BIG-IP.Migration.Assistant.Setup.1.0.4-beta.exe )

**Comment by gakadjame** [comment]
@labilbo  Hello, I'm happy, it's OK the problem has been solved with this patch. thank you very much, greet the whole team.

**Comment by labilbo** [comment]
Great, happy to hear it- thanks @gakadjame!
