### ISSUE TITLE
RFE - Would love support for 1-nic machines

### ISSUE THREAD

**Issue by jmcalalang** [f5devcentral/f5-big-ip-migration-assistant#4]
Cant Specify port on hostname/ip for ``Device Address``. Use case is someone migrating clouds, or from/to a 1NIC machine.

<img width="1099" alt="f5_big-ip_migration_assistant__v1_0_3__and_new_issue_ _f5devcentral_f5-big-ip-migration-assistant" src="https://user-images.githubusercontent.com/20847865/37388992-cf1e51f4-271f-11e8-945f-2cc702aee79e.png">

**Comment by labilbo** [comment]
Thanks for the suggestion @jmcalalang, this will be fixed in v1.0.4 (non-beta build) targeted for 4/2 release.

**Comment by labilbo** [comment]
Fixed in v1.0.4
