### ISSUE TITLE
Why is licensing required for vCMP guests?

### ISSUE THREAD

**Issue by dennisjalbertwork** [f5devcentral/f5-big-ip-migration-assistant#7]
When the destination is a vCMP guest, why do we have to enter a reg key for the host? Shouldn't this be unnecessary since the licensing is already done on the host? 

Also, as someone pointed out in issue #5, it hangs on this step for about an hour for me. When it finally finishes, it requires me to enter the mgmt IP again before proceeding.

**Comment by labilbo** [comment]
You're absolutely right, the reg key should not be required in that case- we'll get that patched for the next release.  Thanks for the heads up.

**Comment by labilbo** [comment]
Fixed in v1.0.4
