### ISSUE TITLE
Encryption passphrase not being set properly

### ISSUE THREAD

**Issue by dennisjalbertwork** [f5devcentral/f5-big-ip-migration-assistant#8]
Sources: 8900 & 3900 running 12.1.3.2
Destinations: vCMP guests running 12.1.3.2
A tmsh load sys config shows:
01071769:3: Decryption of the field (cookie_encryption_passphrase) for object (/Common/cookie) failed.
Unexpected Error: Validating configuration process failed.
I chose to keep the master encryption passphrase and copied it from the device which I migrated. It doesn't seem like it worked though. I've done a bunch more testing and I think I've proved the problem is with the migration utility.
I tried using the platform-migrate command after the migration failure, but it has the same error about the cookie encryption passphrase. I then double checked my device names and IPs and ran the f5mku -K command on the source device again to make sure I had the right passphrase and everything was good. I wanted to make sure I could do a migration manually so I restored my new guest to a default config, ran re-key'ed it myself with f5mku -r xxxx and then loading the ucs manually. It gave me an error about the interfaces as expected due to the platform differences, but it seemed to get past the cookie encryption passphrase error which we've been seeing. I then reset the guest back to defaults, made sure to set the passphrase manually on the new device, and then used the tool thinking I could help it out with that part, but it seems like the tool overwrote they key which I set manually and messed it up again. It failed with the same cookie encryption passphrase error again. So the problem is that the tool is trying to rekey the device, but it isn't doing it properly with the key that I give it. It works fine if I don't use the tool and set the passphrase myself and load the config manually.

**Comment by labilbo** [comment]
Thanks @dennisjalbertwork, we're working on a repro and will keep you apprised as to the progress on this issue

**Comment by fbonds** [comment]
I just tried to reproduce this and could not.  

@dennisjalbertwork please confirm my repro steps as being same/equiv to what you're doing.

Environment:
3900 & vCMP guest both running v12.1.3.2

1. On both 3900 & vCMP guest, set master keys to different known good values with "modify /sys crypto master-key prompt-for-password"
2. With F5 Migration Assistant v1.0.4 (~F5MA), added both devices (3900 & vCMP guest)
3. With F5MA, created UCS Archive from 3900 using configured master-key
4. With F5MA, performed migration to vCMP guest

This completed successfully without error.  On the vCMP guest console before and after, I ran "tmsh load sys config" also without error.  

I want to get a good repro of the issue, please let me know if I'm not doing something you are.  

Thanks!

**Comment by dennisjalbertwork** [comment]
In step 1, I didn’t use the tmsh command. I used the f5mku command to do the same thing. Is there a difference?

Dennis Jalbert
F5 LTM/GTM Support
Security Operations
F5 FAQ<http://f5.lmig.com/faq> | Cert FAQ<https://myconnections.lmig.com/groups/certificate-management-services/blog/2017/09/08/cert-faq>
Get notifications for F5 Upgrades<https://myconnections.lmig.com/groups/f5-load-balancing>

**Comment by fbonds** [comment]
Unrelated to F5MA, I do see this technical article that seems to imply bad things may happen using that command on a vCMP host or guest.

https://devcentral.f5.com/articles/working-with-masterkeys

Re:
"How to modify MasterKey
 
As explained in the SOL it’s possible to modify the master key of the device with the following command:
f5mku -r 
 
There are two bad behaviors of this command:
- If there are already configuration items with encrypted parameter, the bigip is unable to load the configuration. We have to remove SSL key passphrase encryption as explained in the SOL14302: Replacing a VIPRION chassis that has one or more blades installed.
- **_On a vCMP Host or Guest after executing the command the device become unstable._**"

**Comment by labilbo** [comment]
@dennisjalbertwork I was under the impression that it should strip that out, but given what you're seeing it sounds like a potential issue with the tmsh command.  I'm forwarding this on to the team that owns it, and will let you know as soon as I hear back

**Comment by jon-gross-f5** [comment]
I'm sorry for the lack of response on this, we are pausing development of this tool.  We will update you when the situation changes.
