### ISSUE TITLE
Failed to process UCS archive

### ISSUE THREAD

**Issue by tkam8** [f5devcentral/f5-big-ip-migration-assistant#9]
##### ISSUE TYPE

 - UCS generation 

##### F5 MIGRATION ASSISTANT VERSION
```
1.0.4
```
##### BIG-IP VERSION
```
12.1.3
```
##### SUMMARY
I have two devices in a working HA pair and they are successfully added in the tool. However, I am only able to  generate the UCS of the Active unit. The secondary unit times out with below timeout error. 

Any other logs to check? 
If this is by design, we should document and also not allow ucs generation on the secondary BIG-IP so that the files don't pile up. 

##### STEPS TO REPRODUCE

1. Add healthy BIG-IP devices
2. Attempt to generate and download UCS of the secondary unit
3. UCS will be created but the tool is not able to retrieve/download the UCS nor delete it from BIG-IP. 

##### EXPECTED RESULTS

The ucs file can be obtained from either the standby or active unit. 

##### ACTUAL RESULTS

The tool times out trying to retrieve UCS file, the generated UCS remains on the BIG-IP. 
![image](https://user-images.githubusercontent.com/19481266/40100224-2a9086c6-591e-11e8-9f6f-0e2f3745ac73.png)

Failed run on secondary unit: /var/log/audit:
May 16 14:54:12 bigipi2k-191 notice icrd_child[30959]: 01420002:5: AUDIT - pid=30959 user=admin folder=/Common module=(tmos)# status=[Command OK] cmd_data=save sys ucs bigipi2k-191.local_20180516.ucs

Successful run on active unit: /var/log/audit:
May 16 15:00:51 bigipi2k-192 notice icrd_child[12561]: 01420002:5: AUDIT - pid=12561 user=admin folder=/Common module=(tmos)# status=[Command OK] cmd_data=save sys ucs bigipi2k-192.local_20180516.ucs
May 16 15:01:30 bigipi2k-192 notice icrd_child[12561]: 01420002:5: AUDIT - pid=12561 user=admin folder=/Common module=(tmos)# status=[Command OK] cmd_data=run util unix-mv /var/local/ucs/bigipi2k-192.local_20180516.ucs /shared/images/bigipi2k-192.local_20180516.ucs
May 16 15:01:36 bigipi2k-192 notice icrd_child[12561]: 01420002:5: AUDIT - pid=12561 user=admin folder=/Common module=(tmos)# status=[Command OK] cmd_data=run util unix-rm /shared/images/bigipi2k-192.local_20180516.ucs

##### TROUBLESHOOTING

removed/re-added the secondary device, same issue

checked known documentation/past issues
https://devcentral.f5.com/articles/welcome-to-the-f5-big-ip-migration-assistant-29191
https://github.com/f5devcentral/f5-big-ip-migration-assistant/issues?q=is%3Aissue+is%3Aclosed

**Comment by labilbo** [comment]
Thanks for reporting this @tkam8- we'll look into it

**Comment by jon-gross-f5** [comment]
I apologize for the lack of response, we have halted development of this tool.  We will notify you when development resumes.
